languageCode = 'en-AU'
title = 'NCSG Introduction Slides'
theme = "github.com/dzello/reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
